Online Hotel managment System/Controllers/EmpController.cs
 using Microsoft.AspNetCore.Mvc;
using Online_Hotel_Managment_System.Models;

namespace Online_Hotel_Managment_System.Controllers
{
    public class EmpController : Controller
    {
        public EmpController(AppDBContext DB) {
        this.DB = DB;
        }
        private readonly AppDBContext DB;

        public IActionResult Index()
        {
            //list go to view
            IEnumerable<Employee> EmpList = DB.employees;
            return View(EmpList);
        }
        //get
        public IActionResult NewEmp()
        {
            //list go to view
            return View();
        }//delete
       
        //get
        public IActionResult Edit(int? id)
        {
          var item=DB.employees.Find(id);
            return View(item);
        }
        //posts
        [HttpPost]
        public IActionResult Edit(Employee employee)
        {
            if (employee.Emp_Name.Length <= 1)
            {
                ModelState.AddModelError("EmployeeError", "invalidname");
            }
            if (employee.job_Description.Length <= 1)
            {
                ModelState.AddModelError("EmployeeError", "invalidname");
            }
            if (ModelState.IsValid)
            {
                    
                DB.employees.Update(employee);
                DB.SaveChanges();
                //list go to view
                return RedirectToAction("Index");
            }
            else
            {
                return View(employee);
            }
        }
        //post
        [HttpPost]
        public IActionResult NewEmp(Employee employee)
        {
            //if (employee.Emp_Name.Length <= 1)
            //{
            //    ModelState.AddModelError("EmployeeError","invalidname")  ;     
            //}
            //if (employee.job_Description.Length <= 1)
            //{
            //    ModelState.AddModelError("EmployeeError", "invalidname");
            //}
            //if (ModelState.IsValid)
            //{
            //    DB.employees.Add(employee);
            //    DB.SaveChanges();
            //    //list go to view
            //    return RedirectToAction("Index");
            //}
            //else { 
            //    return View(employee);
            //

            DB.employees.Add(employee);
            DB.SaveChanges();
            //list go to view
            return RedirectToAction("Index");
        }

        //Delete
        public IActionResult delete(int? id)
        { 
                var item=DB.employees.Find(id);
                DB.employees.Remove(item);
                DB.SaveChanges();
                //list go to view
                return RedirectToAction("Index");
          
        }
    }
}

Online Hotel managment System/Views/Emp/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Employee;
<h1>Edit tthe Employee'sData</h1>

<form method="post" asp-action="Edit">
  @*  <div asp-validation-summary="All"></div>*@
    <div class="form-group">
        <label asp-for="Emp_Name">Emp_Name</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" asp-for="Emp_Name">
   @*     <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
    <span asp-validation-for="Emp_Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address">Address </label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="enter your address" asp-for="Address">
    </div>
    <span asp-validation-for=" Address" class="text-danger"></span>
    <div class="form-group">
        <label asp-for="job_Description">job_Description </label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="job_Description" asp-for="job_Description">
    </div>
    <span asp-validation-for="job_Description" class="text-danger"></span>
    <div class="form-group">
        <label asp-for="HotelId">Hotel_ID</label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Hotel_ID" asp-for="HotelId">
    </div>
    <span asp-validation-for="HotelId" class="text-danger"></span>
    <br/>
    <button type="submit" class="btn btn-primary">Update</button>

</form>

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Online Hotel managment System/Views/Emp/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<Employee>

<h1 color="red">Welcome , our Employee</h1>
<button type="submit" class="btn btn-primary"><a class="nav-link text-dark" asp-area="" asp-controller="Emp" asp-action="NewEmp">ADD</a></button>
<br />
<br />
<br />
<br />
<br />
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Employee name</th>
            <th scope="col">Address</th>
            <th scope="col">Job_Description</th>
            <th scope="col">Hotel_ID</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>

        @foreach(var item in Model)
  
          {  <tr>
                <th>@item.Emp_ID</th>
                <td>@item.Emp_Name</td>
                <td>@item.Address</td>
                <td>@item.job_Description</td>
                <td>@item.HotelId</td>
                <td>
                    <a asp-action="Edit" asp-controller="Emp"  class="btn btn-light" asp-route-Id="@item.Emp_ID">Update</a>
                    <a asp-action="delete" asp-controller="Emp" class="btn btn-light" asp-route-Id="@item.Emp_ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>


<style>
    h1 {
        text-align: center;
    }
</style>

Online Hotel managment System/Views/Emp/NewEmp.cshtml
@{
    ViewData["Title"] = "NewEmp";
}
@model Employee;
<h1>Registration  A NewEmp</h1>

<form method="post">
  @*  <div asp-validation-summary="All"></div>*@
    <div class="form-group">
        <label asp-for="Emp_Name">Emp_Name</label>
        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" asp-for="Emp_Name">
   @*     <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>*@
    <span asp-validation-for="Emp_Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Address">Address </label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="enter your address" asp-for="Address">
    </div>
    <span asp-validation-for=" Address" class="text-danger"></span>
    <div class="form-group">
        <label asp-for="job_Description">job_Description </label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="job_Description" asp-for="job_Description">
    </div>
    <span asp-validation-for="job_Description" class="text-danger"></span>
    <div class="form-group">
        <label asp-for="HotelId">Hotel_ID</label>
        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Hotel_ID" asp-for="HotelId">
    </div>
    <span asp-validation-for="HotelId" class="text-danger"></span>
    <br/>
    <button type="submit" class="btn btn-primary">Save</button>

</form>

@section Scripts{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}